channels:
- conda-forge
dependencies:
- python=3.11.10
- pip<=23.3.1
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.1.2
  - numpy==2.3.5
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==17.0.0
  - scikit-learn==1.7.2
  - scipy==1.16.3
name: mlflow-env
